#!/usr/bin/env python3
import time
from pynput import mouse

# config
timeout = 10

def jiggle():
    m.move(5, -5)
    time.sleep(0.1)
    m.move(-5, 5)

if __name__ == '__main__':
    m = mouse.Controller()

    last = m.position
    timer = 0
    while True:
        pos = m.position
        if pos != last:
            last = pos
            timer = 0
        else:
            timer += 1

        if timer > timeout:
            jiggle()
            timer = 0

        time.sleep(1)
